claro_forum:
    resource: "@ClarolineForumBundle/Controller/ForumController.php"
    type:     annotation
    prefix:   /

claro_forum_widget:
    resource: "@ClarolineForumBundle/Controller/WidgetController.php"
    type:     annotation
    prefix:   /