services:
    claroline.listener.forum_listener:
        class: Claroline\ForumBundle\Listener\ForumListener
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: kernel.event_listener, event: create_form_claroline_forum, method: onCreateForm }
            - { name: kernel.event_listener, event: create_claroline_forum, method: onCreate }
            - { name: kernel.event_listener, event: open_claroline_forum, method: onOpen }
            - { name: kernel.event_listener, event: copy_claroline_forum, method: onCopy }
            - { name: kernel.event_listener, event: delete_claroline_forum, method: onDelete }
            - { name: kernel.event_listener, event: plugin_options_clarolineforum, method: onAdministrate }
            - { name: kernel.event_listener, event: resource_claroline_forum_to_template, method: onExportTemplate }
            - { name: kernel.event_listener, event: resource_claroline_forum_from_template, method: onImportTemplate }
            - { name: kernel.event_listener, event: delete_user, method: onDeleteUser }
            - { name: kernel.event_listener, event: resource_created_claroline_forum, method: onResourceCreated }
